// GERADO por tools/export-art.mjs e ajustado à mão na v1.4.0 (pássaros em
// 5 espécies de 56x32). NÃO rodar export-art --force: sobrescreveria a arte
// nova de art/*.svg com o gerador antigo (SvgSprites.js, aposentado).
// Dimensões de rasterização dos arquivos art/*.svg (1:1 com o viewBox).
export const ART_MANIFEST = {
  'rhino-run-0': { w: 96, h: 64 },
  'rhino-run-1': { w: 96, h: 64 },
  'rhino-run-2': { w: 96, h: 64 },
  'rhino-face-full': { w: 60, h: 60 },
  'rhino-face-empty': { w: 60, h: 60 },
  'fury-fire-full': { w: 60, h: 60 },
  'fury-fire-empty': { w: 60, h: 60 },
  'animal-lion': { w: 70, h: 56 },
  'animal-lion-run-1': { w: 70, h: 56 },
  'animal-zebra': { w: 76, h: 50 },
  'animal-zebra-air': { w: 76, h: 50 },
  'animal-monkey': { w: 48, h: 56 },
  'animal-monkey-air': { w: 48, h: 56 },
  'animal-giraffe': { w: 60, h: 90 },
  'animal-giraffe-run-1': { w: 60, h: 90 },
  'animal-bird-macaw': { w: 56, h: 32 },
  'animal-bird-macaw-flap': { w: 56, h: 32 },
  'animal-bird-owl': { w: 56, h: 32 },
  'animal-bird-owl-flap': { w: 56, h: 32 },
  'animal-bird-cockatiel': { w: 56, h: 32 },
  'animal-bird-cockatiel-flap': { w: 56, h: 32 },
  'animal-bird-toucan': { w: 56, h: 32 },
  'animal-bird-toucan-flap': { w: 56, h: 32 },
  'animal-bird-jay': { w: 56, h: 32 },
  'animal-bird-jay-flap': { w: 56, h: 32 },
  // v1.7.0 — Fúria Total (mesmo canvas do rinoceronte normal, troca direta)
  'rhino-fire-run-0': { w: 96, h: 64 },
  'rhino-fire-run-1': { w: 96, h: 64 },
  'rhino-fire-run-2': { w: 96, h: 64 },
  // v1.8.0 — skins: SAÍRAM do manifesto. Os frames (rig fixo de 96x64) são
  // derivados do SkinRegistry no preload do BootScene — assim a página
  // /?setup só reescreve o registry, sem tocar aqui.
  // v1.7.0 — inimigos por bioma (art2/ aprovado, dimensões 1:1 com o viewBox)
  'enemy-zookeeper': { w: 48, h: 68 },
  'enemy-zookeeper-run-1': { w: 48, h: 68 },
  'enemy-peacock': { w: 60, h: 54 },
  'enemy-peacock-run-1': { w: 60, h: 54 },
  'enemy-ostrich': { w: 64, h: 80 },
  'enemy-ostrich-run-1': { w: 64, h: 80 },
  'enemy-eagle': { w: 64, h: 36 },
  'enemy-eagle-flap': { w: 64, h: 36 },
  'enemy-hyena': { w: 66, h: 46 },
  'enemy-hyena-run-1': { w: 66, h: 46 },
  'enemy-buffalo': { w: 86, h: 56 },
  'enemy-buffalo-run-1': { w: 86, h: 56 },
  'enemy-jaguar': { w: 80, h: 46 },
  'enemy-jaguar-run-1': { w: 80, h: 46 },
  'enemy-snake': { w: 72, h: 26 },
  'enemy-snake-alt': { w: 72, h: 26 },
  'enemy-croc': { w: 92, h: 38 },
  'enemy-croc-alt': { w: 92, h: 38 },
  'enemy-hippo': { w: 88, h: 58 },
  'enemy-hippo-run-1': { w: 88, h: 58 },
  'enemy-manedwolf': { w: 76, h: 62 },
  'enemy-manedwolf-air': { w: 76, h: 62 },
  'enemy-bluebird': { w: 60, h: 36 },
  'enemy-bluebird-flap': { w: 60, h: 36 },
  'enemy-jabiru': { w: 84, h: 44 },
  'enemy-jabiru-flap': { w: 84, h: 44 },
  'enemy-capybara': { w: 70, h: 42 },
  'enemy-capybara-run-1': { w: 70, h: 42 },
  'enemy-car': { w: 108, h: 46 },
  'enemy-car-alt': { w: 108, h: 46 },
  'enemy-police': { w: 108, h: 48 },
  'enemy-police-alt': { w: 108, h: 48 },
  'enemy-person': { w: 40, h: 62 },
  'enemy-person-run-1': { w: 40, h: 62 },
  'enemy-suit': { w: 42, h: 64 },
  'enemy-suit-run-1': { w: 42, h: 64 },
  'enemy-plane': { w: 120, h: 42 },
  'enemy-plane-alt': { w: 120, h: 42 },
  'enemy-drone': { w: 56, h: 36 },
  'enemy-drone-alt': { w: 56, h: 36 },
  'enemy-pickup': { w: 132, h: 56 },
  'enemy-pickup-alt': { w: 132, h: 56 },
  'enemy-scooter': { w: 96, h: 58 },
  'enemy-scooter-alt': { w: 96, h: 58 },
  // v1.7.0 — o caçador do portão-fortaleza (boss; vigia ↔ pose de mira)
  'boss-hunter': { w: 64, h: 72 },
  'boss-hunter-aim': { w: 64, h: 72 },
  // v1.8.5 — bosses novos (mesmo rig 64x72 do caçador do zoo)
  'boss2-hunter': { w: 64, h: 72 },
  'boss2-hunter-aim': { w: 64, h: 72 },
  'boss3-hunter': { w: 64, h: 72 },
  'boss3-hunter-aim': { w: 64, h: 72 },
  // v1.8.7 — Estado de Alerta: o elenco dos distritos da cidade (dimensões
  // 1:1 com os ANIMAL_SPECS do Constants — o contrato é o spec, não a arte)
  'enemy-viralata': { w: 62, h: 42 },
  'enemy-viralata-run-1': { w: 62, h: 42 },
  'enemy-gatobeco': { w: 52, h: 40 },
  'enemy-gatobeco-air': { w: 52, h: 40 },
  'enemy-pombo': { w: 48, h: 34 },
  'enemy-pombo-flap': { w: 48, h: 34 },
  'enemy-reporter': { w: 44, h: 64 },
  'enemy-reporter-run-1': { w: 44, h: 64 },
  'enemy-pipa': { w: 56, h: 56 },
  'enemy-pipa-alt': { w: 56, h: 56 },
  'enemy-helinews': { w: 110, h: 48 },
  'enemy-helinews-alt': { w: 110, h: 48 },
  'enemy-k9': { w: 64, h: 46 },
  'enemy-k9-air': { w: 64, h: 46 },
  'enemy-tropa': { w: 48, h: 68 },
  'enemy-tropa-run-1': { w: 48, h: 68 },
  'enemy-dronezig': { w: 56, h: 36 },
  'enemy-dronezig-alt': { w: 56, h: 36 },
  'enemy-dronesent': { w: 60, h: 44 },
  'enemy-dronesent-alt': { w: 60, h: 44 },
  // v1.8.7 — o Comandante da Muralha (mesmo rig 64x72 dos caçadores)
  'muralha-hunter': { w: 64, h: 72 },
  'muralha-hunter-aim': { w: 64, h: 72 },
  // v1.8.10 — "As Areias do Tempo": o elenco do deserto (dimensões 1:1 com
  // os ANIMAL_SPECS do Constants — o contrato é o spec, não a arte)
  'enemy-camelo': { w: 90, h: 78 },
  'enemy-camelo-run-1': { w: 90, h: 78 },
  'enemy-abutre': { w: 66, h: 40 },
  'enemy-abutre-flap': { w: 66, h: 40 },
  'enemy-naja': { w: 64, h: 46 },
  'enemy-naja-alt': { w: 64, h: 46 },
  'enemy-flamingo': { w: 78, h: 40 },
  'enemy-flamingo-flap': { w: 78, h: 40 },
  'enemy-mumia': { w: 46, h: 66 },
  'enemy-mumia-run-1': { w: 46, h: 66 },
  'enemy-escaravelho': { w: 52, h: 32 },
  'enemy-escaravelho-run-1': { w: 52, h: 32 },
  'enemy-chacal': { w: 68, h: 46 },
  'enemy-chacal-air': { w: 68, h: 46 },
  'enemy-falcao': { w: 62, h: 36 },
  'enemy-falcao-alt': { w: 62, h: 36 },
  'enemy-arqueiro': { w: 52, h: 64 },
  'enemy-arqueiro-alt': { w: 52, h: 64 },
  // v1.8.10 — o Faraó de Bronze (mesmo rig 64x72 dos caçadores; a "arma"
  // é o cajado-uás — a luz do Espelho de Rá sai da mira em (5,30))
  'farao-hunter': { w: 64, h: 72 },
  'farao-hunter-aim': { w: 64, h: 72 },
};
